"""Prometheus metrics integration for Strategy Agents service."""

import logging

from prometheus_client import Histogram

from services.shared.metrics import signal_generated_total, start_metrics_server

logger = logging.getLogger(__name__)

strategy_run_duration_seconds = Histogram(
    "strategy_run_duration_seconds",
    "Duration of strategy runs",
    ["strategy"],
    buckets=[1, 5, 10, 30, 60, 120, 300],
)


def init_metrics():
    """Start Prometheus metrics server on port 9103."""
    start_metrics_server(9103)


def on_signal_generated(strategy_name: str):
    """Record a signal generated by a strategy."""
    try:
        signal_generated_total.inc()
    except Exception as e:
        logger.debug(f"Metrics error (signal_generated): {e}")


def on_strategy_run(duration_seconds: float):
    """Record a strategy run duration in seconds."""
    try:
        strategy_run_duration_seconds.observe(duration_seconds)
    except Exception as e:
        logger.debug(f"Metrics error (strategy_run): {e}")
