"""Prometheus metrics integration for Strategy Agents service."""

import logging

from prometheus_client import Counter, Histogram, start_http_server

logger = logging.getLogger(__name__)

# ── Shared metrics (inlined from services.shared.metrics) ──────────────
data_collected_total = Counter('data_collected_total', 'Total data collected', ['service', 'source'])
features_computed_total = Counter('features_computed_total', 'Total features computed', ['service'])
prediction_latency_seconds = Histogram('prediction_latency_seconds', 'Prediction latency', ['model'], buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 5.0])
sentiment_analysis_total = Counter('sentiment_analysis_total', 'Sentiment analyses', ['source'])
signal_generated_total = Counter('signal_generated_total', 'Trading signals generated')
trade_executed_total = Counter('trade_executed_total', 'Trades executed')
db_query_latency_seconds = Histogram('db_query_latency_seconds', 'DB query latency', buckets=[0.001, 0.01, 0.1, 0.5, 1.0])
redis_publish_total = Counter('redis_publish_total', 'Redis messages published', ['stream'])

# ── Service-specific metrics ──────────────────────────────────────────
strategy_run_duration_seconds = Histogram(
    "strategy_run_duration_seconds",
    "Duration of strategy runs",
    ["strategy"],
    buckets=[1, 5, 10, 30, 60, 120, 300],
)


def init_metrics(port: int = 9103):
    """Start Prometheus metrics server on given port."""
    try:
        start_http_server(port)
        logger.info(f"Prometheus metrics server started on port {port}")
    except OSError as e:
        logger.warning(f"Could not start metrics server on port {port}: {e}")


def on_signal_generated(strategy_name: str):
    """Record a signal generated by a strategy."""
    try:
        signal_generated_total.inc()
    except Exception as e:
        logger.debug(f"Metrics error (signal_generated): {e}")


def on_strategy_run(duration_seconds: float):
    """Record a strategy run duration in seconds."""
    try:
        strategy_run_duration_seconds.observe(duration_seconds)
    except Exception as e:
        logger.debug(f"Metrics error (strategy_run): {e}")
